### ISSUE TITLE
What about back end 

### ISSUE THREAD

**Issue by jishnurajm** [hetsuthar028/Farming-App#12]
I wish to test your app . How to setup it's back end . Will you please give me a detailed explanation

**Comment by hetsuthar028** [comment]
### To have this app up and running, you'll have to configure few things mentioned below:

- Firebase project 
  Get the package.json file generated from the Firebase console and replace the existing file with the newly generated
- Add Android Studio SHA Fingerprint to the Firebase project console
- Allow Firebase Authentication using Google, Email, Phone
- Get an API from `https://openweathermap.org/api` and replace with the new one
- Get an API from `https://api.data.gov.in/` and put it inside the APMC API file
- Setup the Firebase firestore with some necessary documents
- Check for app's permissions and SDK version

**Comment by jishnurajm** [comment]
Thanks

**Comment by Akash5473** [comment]
But how we add any products for sell or buy

**Comment by hetsuthar028** [comment]
> But how we add any products for sell or buy

There isn't a dashboard to add products as of now but surely you can create a screen which allows the main user to add products into the Firebase.

**Comment by Akash5473** [comment]
So sir I would like to ask that what was schema for the products you have
used in your project for the products in the firebase. Since I was trying
to add products in firebase but the app got crash. I request you to please
help me.

**Comment by Akash5473** [comment]
So the main user how add the products in the firebase sir.

**Comment by Akash5473** [comment]
Sir Please reply it is important for me.
Please give your some time.

**Comment by Akash5473** [comment]
Sir,please help me. I am unable to add the product in the firebase.
